# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Code\Python\WiProgram\SetingMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(473, 573)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TreeWidget = QtWidgets.QTreeWidget(Form)
        self.TreeWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.TreeWidget.setDragEnabled(True)
        self.TreeWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.TreeWidget.setAnimated(False)
        self.TreeWidget.setAllColumnsShowFocus(False)
        self.TreeWidget.setWordWrap(False)
        self.TreeWidget.setHeaderHidden(False)
        self.TreeWidget.setObjectName("TreeWidget")
        self.TreeWidget.header().setVisible(True)
        self.TreeWidget.header().setCascadingSectionResizes(False)
        self.TreeWidget.header().setDefaultSectionSize(70)
        self.TreeWidget.header().setHighlightSections(False)
        self.TreeWidget.header().setMinimumSectionSize(50)
        self.TreeWidget.header().setSortIndicatorShown(False)
        self.TreeWidget.header().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.TreeWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Add = QtWidgets.QPushButton(Form)
        self.Add.setObjectName("Add")
        self.horizontalLayout.addWidget(self.Add)
        self.Confirmed = QtWidgets.QPushButton(Form)
        self.Confirmed.setObjectName("Confirmed")
        self.horizontalLayout.addWidget(self.Confirmed)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.TreeWidget.setSortingEnabled(False)
        self.TreeWidget.headerItem().setText(0, _translate("Form", "Name"))
        self.TreeWidget.headerItem().setText(1, _translate("Form", "Tupe"))
        self.Add.setText(_translate("Form", "Add"))
        self.Confirmed.setText(_translate("Form", "Confirmed"))
