# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Code\Python\WiProgram\ui\dialog\InputData.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InputData(object):
    def setupUi(self, InputData):
        InputData.setObjectName("InputData")
        InputData.resize(342, 99)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        InputData.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(InputData)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LineName = QtWidgets.QLineEdit(InputData)
        self.LineName.setObjectName("LineName")
        self.horizontalLayout_2.addWidget(self.LineName)
        self.CheckBox = QtWidgets.QCheckBox(InputData)
        self.CheckBox.setObjectName("CheckBox")
        self.horizontalLayout_2.addWidget(self.CheckBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LineData = QtWidgets.QLineEdit(InputData)
        self.LineData.setPlaceholderText("")
        self.LineData.setObjectName("LineData")
        self.horizontalLayout.addWidget(self.LineData)
        self.ToolButton = QtWidgets.QToolButton(InputData)
        self.ToolButton.setObjectName("ToolButton")
        self.horizontalLayout.addWidget(self.ToolButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(InputData)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(InputData)
        self.buttonBox.accepted.connect(InputData.accept) # type: ignore
        self.buttonBox.rejected.connect(InputData.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(InputData)

    def retranslateUi(self, InputData):
        _translate = QtCore.QCoreApplication.translate
        InputData.setWindowTitle(_translate("InputData", "Dialog"))
        self.LineName.setPlaceholderText(_translate("InputData", "Name"))
        self.CheckBox.setText(_translate("InputData", "Auto Name"))
        self.ToolButton.setText(_translate("InputData", "..."))
