# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Code\Python\WiProgram\ui\dialog\MacrosEditor.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MacrosEditor(object):
    def setupUi(self, MacrosEditor):
        MacrosEditor.setObjectName("MacrosEditor")
        MacrosEditor.resize(280, 500)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        MacrosEditor.setFont(font)
        MacrosEditor.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        MacrosEditor.setSizeGripEnabled(False)
        MacrosEditor.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(MacrosEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TreeWidget = QtWidgets.QTreeWidget(MacrosEditor)
        self.TreeWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.TreeWidget.setAcceptDrops(True)
        self.TreeWidget.setDragEnabled(True)
        self.TreeWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.TreeWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.TreeWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.TreeWidget.setRootIsDecorated(False)
        self.TreeWidget.setItemsExpandable(True)
        self.TreeWidget.setObjectName("TreeWidget")
        self.verticalLayout.addWidget(self.TreeWidget)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.StartRecord = QtWidgets.QPushButton(MacrosEditor)
        self.StartRecord.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.StartRecord.setObjectName("StartRecord")
        self.gridLayout.addWidget(self.StartRecord, 0, 0, 1, 1)
        self.SelectAll = QtWidgets.QPushButton(MacrosEditor)
        self.SelectAll.setObjectName("SelectAll")
        self.gridLayout.addWidget(self.SelectAll, 0, 1, 1, 1)
        self.SaveMacros = QtWidgets.QPushButton(MacrosEditor)
        self.SaveMacros.setObjectName("SaveMacros")
        self.gridLayout.addWidget(self.SaveMacros, 1, 0, 1, 1)
        self.Clear = QtWidgets.QPushButton(MacrosEditor)
        self.Clear.setObjectName("Clear")
        self.gridLayout.addWidget(self.Clear, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(MacrosEditor)
        QtCore.QMetaObject.connectSlotsByName(MacrosEditor)
        MacrosEditor.setTabOrder(self.TreeWidget, self.StartRecord)
        MacrosEditor.setTabOrder(self.StartRecord, self.SelectAll)
        MacrosEditor.setTabOrder(self.SelectAll, self.SaveMacros)
        MacrosEditor.setTabOrder(self.SaveMacros, self.Clear)

    def retranslateUi(self, MacrosEditor):
        _translate = QtCore.QCoreApplication.translate
        MacrosEditor.setWindowTitle(_translate("MacrosEditor", "Macros Editor"))
        self.TreeWidget.headerItem().setText(0, _translate("MacrosEditor", "Action"))
        self.TreeWidget.headerItem().setText(1, _translate("MacrosEditor", "Key"))
        self.StartRecord.setText(_translate("MacrosEditor", "Start Record"))
        self.SelectAll.setText(_translate("MacrosEditor", "Select All"))
        self.SaveMacros.setText(_translate("MacrosEditor", "Save Macros"))
        self.Clear.setText(_translate("MacrosEditor", "Clear"))
