# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Code\Python\WiProgram\ui\dialog\Macros.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(280, 500)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        Dialog.setFont(font)
        Dialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TreeWidget = QtWidgets.QTreeWidget(Dialog)
        self.TreeWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.TreeWidget.setAcceptDrops(True)
        self.TreeWidget.setDragEnabled(True)
        self.TreeWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.TreeWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.TreeWidget.setRootIsDecorated(False)
        self.TreeWidget.setObjectName("TreeWidget")
        self.verticalLayout.addWidget(self.TreeWidget)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.StartRecord = QtWidgets.QPushButton(Dialog)
        self.StartRecord.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.StartRecord.setObjectName("StartRecord")
        self.gridLayout.addWidget(self.StartRecord, 0, 0, 1, 1)
        self.SelectAll = QtWidgets.QPushButton(Dialog)
        self.SelectAll.setObjectName("SelectAll")
        self.gridLayout.addWidget(self.SelectAll, 0, 1, 1, 1)
        self.SaveMacros = QtWidgets.QPushButton(Dialog)
        self.SaveMacros.setObjectName("SaveMacros")
        self.gridLayout.addWidget(self.SaveMacros, 1, 0, 1, 1)
        self.Clear = QtWidgets.QPushButton(Dialog)
        self.Clear.setObjectName("Clear")
        self.gridLayout.addWidget(self.Clear, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.TreeWidget, self.StartRecord)
        Dialog.setTabOrder(self.StartRecord, self.SelectAll)
        Dialog.setTabOrder(self.SelectAll, self.SaveMacros)
        Dialog.setTabOrder(self.SaveMacros, self.Clear)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Macros Record"))
        self.TreeWidget.headerItem().setText(0, _translate("Dialog", "Action"))
        self.TreeWidget.headerItem().setText(1, _translate("Dialog", "Key"))
        self.StartRecord.setText(_translate("Dialog", "Start Record"))
        self.SelectAll.setText(_translate("Dialog", "Select All"))
        self.SaveMacros.setText(_translate("Dialog", "Save Macros"))
        self.Clear.setText(_translate("Dialog", "Clear"))
