# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Code\Python\WiProgram\ui\Painter.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Painter(object):
    def setupUi(self, Painter):
        Painter.setObjectName("Painter")
        Painter.resize(714, 612)
        self.Widget = QtWidgets.QWidget(Painter)
        self.Widget.setObjectName("Widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Widget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.MenuBar = QtWidgets.QFrame(self.Widget)
        self.MenuBar.setStyleSheet("QFrame {\n"
"                background-color: rgba(30, 30, 30, 240);\n"
"                border-radius: 8px;\n"
"                padding: 1px;\n"
"                border: 1px solid rgb(41, 45, 49);\n"
"            }")
        self.MenuBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MenuBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MenuBar.setObjectName("MenuBar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.MenuBar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SelectColor = QtWidgets.QPushButton(self.MenuBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SelectColor.sizePolicy().hasHeightForWidth())
        self.SelectColor.setSizePolicy(sizePolicy)
        self.SelectColor.setMinimumSize(QtCore.QSize(30, 30))
        self.SelectColor.setMaximumSize(QtCore.QSize(30, 30))
        self.SelectColor.setStyleSheet("background-color: rgb(255, 0, 0); border: 2px solid white; border-radius: 5px;")
        self.SelectColor.setText("")
        self.SelectColor.setObjectName("SelectColor")
        self.horizontalLayout.addWidget(self.SelectColor)
        self.SlideWidth = QtWidgets.QSlider(self.MenuBar)
        self.SlideWidth.setMinimumSize(QtCore.QSize(300, 0))
        self.SlideWidth.setMaximumSize(QtCore.QSize(300, 16777215))
        self.SlideWidth.setMinimum(1)
        self.SlideWidth.setMaximum(30)
        self.SlideWidth.setPageStep(2)
        self.SlideWidth.setProperty("value", 5)
        self.SlideWidth.setSliderPosition(5)
        self.SlideWidth.setOrientation(QtCore.Qt.Horizontal)
        self.SlideWidth.setObjectName("SlideWidth")
        self.horizontalLayout.addWidget(self.SlideWidth)
        self.Clear = QtWidgets.QPushButton(self.MenuBar)
        self.Clear.setStyleSheet("color: white; background: #444; border-radius: 5px; padding: 6px; font-size: 14px; font-family: Segoe UI;")
        self.Clear.setObjectName("Clear")
        self.horizontalLayout.addWidget(self.Clear)
        self.Quit = QtWidgets.QPushButton(self.MenuBar)
        self.Quit.setMinimumSize(QtCore.QSize(30, 30))
        self.Quit.setMaximumSize(QtCore.QSize(30, 30))
        self.Quit.setStyleSheet("color: white; background: #c0392b; border-radius: 5px; font-weight: bold;")
        self.Quit.setObjectName("Quit")
        self.horizontalLayout.addWidget(self.Quit)
        self.verticalLayout.addWidget(self.MenuBar, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        Painter.setCentralWidget(self.Widget)

        self.retranslateUi(Painter)
        self.Quit.clicked.connect(Painter.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Painter)
        Painter.setTabOrder(self.SelectColor, self.SlideWidth)
        Painter.setTabOrder(self.SlideWidth, self.Clear)
        Painter.setTabOrder(self.Clear, self.Quit)

    def retranslateUi(self, Painter):
        _translate = QtCore.QCoreApplication.translate
        Painter.setWindowTitle(_translate("Painter", "MainWindow"))
        self.Clear.setText(_translate("Painter", "Clear"))
        self.Quit.setText(_translate("Painter", "✕"))
