# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Code\Python\WiProgram\ui\SelectWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(770, 600)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        Dialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TreeWidget = QtWidgets.QTreeWidget(Dialog)
        self.TreeWidget.setEnabled(True)
        self.TreeWidget.setObjectName("TreeWidget")
        self.verticalLayout.addWidget(self.TreeWidget)
        self.ButtonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.ButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.ButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.ButtonBox.setObjectName("ButtonBox")
        self.verticalLayout.addWidget(self.ButtonBox)

        self.retranslateUi(Dialog)
        self.ButtonBox.accepted.connect(Dialog.accept) # type: ignore
        self.ButtonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.TreeWidget.setSortingEnabled(True)
        self.TreeWidget.headerItem().setText(0, _translate("Dialog", "Title"))
        self.TreeWidget.headerItem().setText(1, _translate("Dialog", "Path"))
        self.TreeWidget.headerItem().setText(2, _translate("Dialog", "Options"))
